version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  rebase-strategy: disabled
  ignore: 
    - dependency-name: "*eslint*"
    - dependency-name: "jest"
    - dependency-name: "postcss"
    - dependency-name: "standard"
    - dependency-name: "@vue/*"
    - dependency-name: "vue-template-compiler"
