name: github-pages
on: 
  push:
    branches:
      - gh-actions

jobs:

  prep-meilisearch: 
    if: github.event_name == 'push' && github.push.paths == 'setup.js'
    runs-on: ubuntu-18.04
    steps:
      - name: Get dataset
        run: npm run get-dataset
      
      - name: Prep MeiliSearch
        run: npm install
        run: npm prep-meili

      
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node- 

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
    env:
      VUE_APP_MEILISEARCH_HOST: ${{ secrets.VUE_APP_MEILISEARCH_HOST }}
      VUE_APP_MEILISEARCH_API_KEY: ${{ secrets.VUE_APP_MEILISEARCH_API_KEY }}
